//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS_Library.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


	public partial class Client_Details
    {
        [Key]
        public string ClientID { get; set; }
        public System.DateTime Date { get; set; }
        public string ClientName { get; set; }
        public string Category { get; set; }
        public string Phone { get; set; }
        public string EmailID { get; set; }
    }
}
