//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS_Library.Models.DataModels
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Doctor_Specialty
    {
        [Key]
        public string SpecialityID { get; set; }
        public string SpecialityName { get; set; }
        public string SpecialityDescription { get; set; }
    }
}
