//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS_Library.Models.DataModels
{
	using Microsoft.EntityFrameworkCore;
	using Microsoft.EntityFrameworkCore.Design;
	using Microsoft.Extensions.Configuration;
	using System;
	using System.IO;

    
    public partial class PMS_Entities : DbContext
    {
        public PMS_Entities(DbContextOptions<PMS_Entities> options)
            : base(options)
        {
        }
    
    
        public virtual DbSet<Client_Billing> Client_Billing { get; set; }
        public virtual DbSet<Client_Categories> Client_Categories { get; set; }
        public virtual DbSet<Client_Details> Client_Details { get; set; }
        public virtual DbSet<Client_Subscription> Client_Subscription { get; set; }
        public virtual DbSet<Client_SubscriptionCodes> Client_SubscriptionCodes { get; set; }
        public virtual DbSet<Doctor_Details> Doctor_Details { get; set; }
        public virtual DbSet<Doctor_Specialty> Doctor_Specialty { get; set; }
        public virtual DbSet<Patient_Details> Patient_Details { get; set; }
        public virtual DbSet<Staff_Details> Staff_Details { get; set; }
        public virtual DbSet<Staff_Roles> Staff_Roles { get; set; }
    }

    public class DesignTimeDbContextFactory : IDesignTimeDbContextFactory<PMS_Entities>
    {
        public PMS_Entities CreateDbContext(string[] args)
        {
            IConfigurationRoot configuration = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile(@Directory.GetCurrentDirectory() + "/../PMS.API/appsettings.json")
                .Build();
            var builder = new DbContextOptionsBuilder<PMS_Entities>();
            var connectionString = configuration.GetConnectionString("DatabaseConnection");
            builder.UseSqlServer(connectionString);
            return new PMS_Entities(builder.Options);
        }
    }
}
