//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS_Library.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Client_Billing
    {
        [Key]
        public string BillingID { get; set; }
        public System.DateTime Date { get; set; }
        public string HospitalID { get; set; }
        public string Subcription { get; set; }
        public double AmountPaid { get; set; }
        public string AmountDue { get; set; }
        public System.DateTime PaidDate { get; set; }
        public string Status { get; set; }
    }
}
