//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS_Library.Models.DataModel
{
    using Microsoft.EntityFrameworkCore;
    
    public partial class PMS_Entities : DbContext
    {
        public PMS_Entities(DbContextOptions<PMS_Entities> options)
            : base(options)
        {
        }
    
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        }
    
        public virtual DbSet<Client_Billing> Client_Billing { get; set; }
        public virtual DbSet<Client_Categories> Client_Categories { get; set; }
        public virtual DbSet<Client_Details> Client_Details { get; set; }
        public virtual DbSet<Client_Subscription> Client_Subscription { get; set; }
        public virtual DbSet<Client_SubscriptionCodes> Client_SubscriptionCodes { get; set; }
        public virtual DbSet<Doctor_Details> Doctor_Details { get; set; }
        public virtual DbSet<Doctor_Specialty> Doctor_Specialty { get; set; }
        public virtual DbSet<Patient_Details> Patient_Details { get; set; }
        public virtual DbSet<Staff_Details> Staff_Details { get; set; }
        public virtual DbSet<User_Auth> User_Auth { get; set; }
        public virtual DbSet<User_Roles> User_Roles { get; set; }
        public virtual DbSet<User_Token> User_Token { get; set; }
    }
}
