//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS_Library.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User_Token
    {
        [Key]
        public string AccessID { get; set; }
        public string EmailID { get; set; }
        public string AccessToken { get; set; }
        public string RefreshToken { get; set; }
        public System.DateTime TokenExpiration { get; set; }

    }
}
