//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS_Library.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User_Auth
    {
        [Key]
        public string LoginId { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public string ClientName { get; set; }
    }
}
